# Generated by Django 4.2.7 on 2023-11-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_employee_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('language_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
